### PR TITLE
Cleanups to help fix CI

### PR DESCRIPTION
**Pull request by nshalman**
## Description

Fix CI

## Why is this needed

CI is broken

## How Has This Been Tested?

- [ ] CI

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by markyjackson-taulia — DISMISSED** [review]

**Comment by nshalman** [comment]
I'm concerned that CI is workin within PRs but broken on main, if that's the case, landing this will be a nice improvement, but won't fix the build for pushing to quay and we'll still need deeper debugging and a follow-up.

**Comment by markyjackson-taulia** [comment]
Please continue with that deeper dive, this is a priority.

**Comment by nshalman** [comment]
Okay, I've managed to trip the intermittent test failure:
```
=== RUN   TestServe/serve_endpoint_success
{"level":"info","ts":1640096102.091404,"caller":"http-server/http_server.go:65","msg":"Starting http server","service":"github.com/tinkerbell/hegel","pkg":"httpserver","port":52000}
    http_server_test.go:934: request failed: Get "http://localhost:52000/_packet/version": dial tcp [::1]:52000: connect: connection refused
=== RUN   TestServe/serve_endpoint_failed
--- FAIL: TestServe (0.00s)
    --- FAIL: TestServe/serve_endpoint_success (0.00s)
    --- PASS: TestServe/serve_endpoint_failed (0.00s)
FAIL
FAIL	github.com/tinkerbell/hegel/http-server	0.025s
?   	github.com/tinkerbell/hegel/metrics	[no test files]
?   	github.com/tinkerbell/hegel/xff	[no test files]
FAIL
```

Flaky tests are the worst. This might require deeper changes to fix that test.

**Comment by nshalman** [comment]
The issue is the use of a hardcoded port
https://github.com/tinkerbell/hegel/blob/main/http-server/http_server_test.go#L914-L915

being assigned to a global variable
https://github.com/tinkerbell/hegel/blob/main/http-server/http_server.go#L26

**Review by markyjackson-taulia — APPROVED** [review]

**Pull request merged**
