### PR TITLE
add vendor-data EC2 style path (like user-data)

### PR DESCRIPTION
**Pull request by displague**
## Description

When "vendordata" is included in the hardware metadata, expose it
through the EC2 path structure.

Although vendor-data does not appear to be an EC2 exposed path, tools
like cloud-init make all of the paths listed in 2009-04-04 available to
scripts and cloud-init takes advantage of these paths, including
vendor-data.

## Why is this needed

Fixes: #62

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by displague** [comment]
I don't believe this has a hard dependency on https://github.com/tinkerbell/tink/pull/579, but it may be worth looking at first.

**Comment by jacobweinstock** [comment]
Anyone more familiar with this code base able to review? @mmlb , @nshalman ?

**Comment by chrisdoherty4** [comment]
@displague Vendor data isn't strictly part of the Equinix metadata standard. I'm not totally sure we should add it. 

Given we're developing the new Hegel metadata standard how would you feel about exposing vendor data in that instead?

**Comment by chrisdoherty4** [comment]
Closing, see #62.

**Pull request closed without merging**
