### PR TITLE
Rebase ENG-8444 splitting main package

### PR DESCRIPTION
**Pull request by Raj-Dharwadkar**
Rebase ENG-8444 split main package to grpc-server, http-server, and hardware

## Description
rebase changes from PR-34 made by kelly deng
Following are changes:
    - main package is split  into three packages: grpc-server, http-server, and hardware. 
    - hardware package includes all hardware related i.e, defining hardware structs, getting and exporting data from tink/cacher.

## Why is this needed

Fixes: #

## How Has This Been Tested?
setup sandbox: build hegel image with these changes and able to provision OS.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by Raj-Dharwadkar** [comment]
Rebase ENG-8444 split main package to grpc-server, http-server, and hardware.

**Review by markyjackson-taulia — DISMISSED** [review]
Awesome job!

**Review by mmlb — CHANGES_REQUESTED** [review]

**Review by markyjackson-taulia — DISMISSED** [review]

**Review by jacobweinstock — DISMISSED** [review]
@Raj-Dharwadkar, this is a great job. Thank you for the time, effort, and energy on this.

**Comment by mmlb** [comment]
> look fine. I imagine it's "better" than what we currently have. it's quite a large PR though with lots of changing/moving parts.
> 
> Just for the record:
> 
> It does feel like we are trading some current complexities/issues for new ones that should have been avoided. Especially since this is not just a quick and easy split of the main package. Things like removing globals, context propagation, graceful shutdowns should have been discussed as some of the design philosophy for this refactor.

Agreed. I don't think we'd want a full refactor atm though so I think the end result being the same is good for incremental progress. It would have been better if the PR itself wasn't one huge commit and instead was smaller obviously correct changes.

**Review by markyjackson-taulia — APPROVED** [review]

**Review by markyjackson-taulia — APPROVED** [review]

**Review by jacobweinstock — APPROVED** [review]

**Review by mmlb — APPROVED** [review]

**Pull request merged**
